'use strict';

/**
 * src/mappers/dlrMapper.js
 * Maps SPARC statuses to internal statuses.
 */

const { MESSAGE_STATUSES } = require('../config/constants');

const STATUS_MAP = {
  'SUBMITTED':          MESSAGE_STATUSES.RCS_SENT,
  'SENT':               MESSAGE_STATUSES.RCS_SENT,
  'DELIVERED':          MESSAGE_STATUSES.RCS_DELIVERED,
  'MESSAGE_DELIVERED':  MESSAGE_STATUSES.RCS_DELIVERED,
  'RCS_DELIVERED':      MESSAGE_STATUSES.RCS_DELIVERED,
  'READ':               MESSAGE_STATUSES.RCS_READ,
  'MESSAGE_READ':       MESSAGE_STATUSES.RCS_READ,
  'RCS_READ':           MESSAGE_STATUSES.RCS_READ,
  'FAILED':             MESSAGE_STATUSES.RCS_DELIVERY_FAILED,
  'MESSAGE_FAILED':     MESSAGE_STATUSES.RCS_DELIVERY_FAILED,
  'RCS_DELIVERY_FAILED': MESSAGE_STATUSES.RCS_DELIVERY_FAILED,
  'UNDELIVERED':        MESSAGE_STATUSES.RCS_DELIVERY_FAILED,
  'EXPIRED':            MESSAGE_STATUSES.RCS_DELIVERY_FAILED,
  'DELETED':            MESSAGE_STATUSES.RCS_DELIVERY_FAILED,
  'REJECTED':           MESSAGE_STATUSES.RCS_DELIVERY_FAILED,

  // SMS statuses (all variants)
  'DELIVERY_SUCCESS':   MESSAGE_STATUSES.SMS_DELIVERED,
  'DELIVERY_FAILURE':   MESSAGE_STATUSES.SMS_DELIVERY_FAILED,
  'SMS_DELIVERED':      MESSAGE_STATUSES.SMS_DELIVERED,
  'SMS_FAILED':         MESSAGE_STATUSES.SMS_DELIVERY_FAILED,
};

// Determine if a status is SMS-based
function isSmsStatus(status) {
  return ['SMS_DELIVERED', 'SMS_DELIVERY_FAILED', 'DELIVERY_SUCCESS', 'DELIVERY_FAILURE', 'SMS_DELIVERED', 'SMS_FAILED'].includes((status || '').toUpperCase());
}

function translateStatus(sparcStatus) {
  const status = (sparcStatus || '').toUpperCase();
  return STATUS_MAP[status] || MESSAGE_STATUSES.RCS_SENT_FAILED;
}

module.exports = { translateStatus, isSmsStatus };
