'use strict';

module.exports = {
  MESSAGE_STATUSES: {
    QUEUED: 'QUEUED',
    RCS_SENT: 'RCS_SENT',
    RCS_SENT_FAILED: 'RCS_SENT_FAILED',
    RCS_DELIVERED: 'RCS_DELIVERED',
    RCS_READ: 'RCS_READ',
    RCS_DELIVERY_FAILED: 'RCS_DELIVERY_FAILED',
    SMS_SENT: 'SMS_SENT',
    SMS_SENT_FAILED: 'SMS_SENT_FAILED',
    SMS_DELIVERED: 'SMS_DELIVERED',
    SMS_DELIVERY_FAILED: 'SMS_DELIVERY_FAILED',
  },
  
  CHANNELS: {
    RCS: 'rcs',
    SMS: 'sms',
  },

  RETRY_CONFIG: {
    MAX_ATTEMPTS: 3,
    DELAYS_MS: [1000, 2000, 3000], // 1s, 2s, 3s
  },

  CONNECTOR_CALLBACK_TIMEOUT_MS: 5000,

  PAYLOAD_TYPES: {
    STATUS: 'CLEVERTAP_STATUS',
    SUGGESTION: 'CLEVERTAP_INTERACTION',
    SMS_DLR: 'CLEVERTAP_SMS_DLR',
  }
};
