'use strict';

module.exports = {
  CHANNELS: {
    RCS: 'rcs',
    SMS: 'sms'
  },
  MESSAGE_STATUSES: {
    RCS_SENT: 'RCS_SENT',
    RCS_DELIVERED: 'RCS_DELIVERED',
    RCS_READ: 'RCS_READ',
    RCS_DELIVERY_FAILED: 'RCS_DELIVERY_FAILED',
    RCS_SENT_FAILED: 'RCS_SENT_FAILED',
    SMS_SENT: 'SMS_SENT',
    SMS_DELIVERED: 'SMS_DELIVERED',
    SMS_DELIVERY_FAILED: 'SMS_DELIVERY_FAILED'
  },
  CONNECTOR_TYPE: 'WEBENGAGE'
};
